name: phf
description: PaperHealth - Security-First Offline Medical Records.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Security & Privacy
  sqflite_sqlcipher: ^3.0.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

  # Architecture & State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Media & IO
  image: ^4.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  google_mlkit_text_recognition: ^0.13.0
  workmanager: ^0.5.2
  
  # Utils
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  cryptography: ^2.9.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  intl: ^0.20.2
  local_auth: ^3.0.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  mockito: ^5.4.6
  sqflite_common_ffi: ^2.4.0+1

  path_provider_platform_interface: any
  plugin_platform_interface: any
  path: any
  local_auth_android: any
  local_auth_darwin: any
  local_auth_windows: any
  image_picker_platform_interface: any
  sqflite_common: any
flutter:
  uses-material-design: true
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata-Bold.ttf
          weight: 700
